### ISSUE TITLE
[Feature request] Add a "Home" button on 404 (when paste has expired/ doesn't exist)

### ISSUE THREAD

**Issue by TehPeGaSuS** [MercanoGlobal/SNIP#11]
Like the text suggest, it'd be nice to have "Back to home" alike button instead having to click on the back arrow of the browser when a paste is not found due to being expired/malformed URL.

**Comment by MercanoGlobal** [comment]
Thanks for the suggestion, nice one!
Please redownload the latest release and test: https://github.com/MercanoGlobal/SNIP/releases

**Comment by TehPeGaSuS** [comment]
I loved it!
The new error page is so cool!
