### ISSUE TITLE
[Feature request] Add a `-dark` variant to each theme

### ISSUE THREAD

**Issue by TehPeGaSuS** [MercanoGlobal/SNIP#12]
Like the title describes, it'd be nice to have some sort of `stikkedizr-dark` to have a dark background variant (easier on the eyes).

Obviously the `Create`, `Create encrypted` and `Recaptcha box` would keep their actual colours (bonus if the Recaptcha box can have a dark backgorund too).

Cheers!

**Comment by MercanoGlobal** [comment]
No other enhancements other than bug fixes will be done to the existing themes.
From a coding standpoint, they are a complete mess, feeling like they were developed by complete beginners, with tons of inconsistencies, missing features, 0 coding standards etc.
Besides the bugs, I did my best to fix a lot of their design issues, but this is as far as we go.

I created a new feature request regarding this, as the only way forward would be to create a new theme that should include the key points I mentioned there.
However, this is no easy task, and it will take time and finesse, but we will see what the future has in store for this project.

I'll close this request.
