### ISSUE TITLE
[Feature request] Notice banner, footer or both

### ISSUE THREAD

**Issue by TehPeGaSuS** [MercanoGlobal/SNIP#15]
I'd love to have the ability to:

- [ ] Create a notice banner like the one at https://privatebin.mooo.com/

- [ ] Create a footer like the one at https://privatebin.mooo.com/

- [ ] Both, if possible, would be preferred

**Comment by MercanoGlobal** [comment]
Closed by https://github.com/MercanoGlobal/SNIP/commit/6621873c7a74d067234b1dbb47fcb0aa34189229

Will not add one for the footer, as this should be more of an individual theme's option, than a core configuration one.
