### ISSUE TITLE
[PostgreSQL] Database error on fresh install

### ISSUE THREAD

**Issue by TehPeGaSuS** [MercanoGlobal/SNIP#2]
Just tried to deploy SNIP and I got this:
![Snip_Database_Error](https://github.com/user-attachments/assets/1c5ed07d-45a3-4569-8eea-29da9061c6d3)
Using Postgresql, database was freshly create, new database user.

**Comment by MercanoGlobal** [comment]
1. Please provide more information about your setup: PHP version, DB engine and version ...
2. The error message gives you the answer. It seems that the database isn't fresh, you have tables in it.
However, we don't use/have access to PostgreSQL in order to test ourselves.

**Comment by TehPeGaSuS** [comment]
> 1. Please provide more information about your setup: PHP version, DB engine and version ...

Operative System: Ubuntu 22.04.5 LTS
PostgreSQL version: PostgreSQL 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)
PHP version: PHP 8.1.2-1ubuntu2.18 (cli) (built: Jun 14 2024 15:52:55) (NTS)

> 2. The error message gives you the answer. It seems that the database isn't fresh, you have tables in it.
>    However, we don't use/have access to PostgreSQL in order to test ourselves.

Tables are created by SNIP itself. the database is fresh. I even deleted and recreated the database 2 times before reporting the issue

**Comment by MercanoGlobal** [comment]
Ok, I dug this a bit more, and we found that Postgre handles existing columns differently than MySQL/MariaDB and doesn't take into account properly the `if (!$this->db->field_exists('ip_address', 'pastes'))` statement for existing tables, which is a big bummer.
So, as we don't have access to Postgre, let's do a blind test.
Create a clean database and in `/application/controllers/Main.php` replace the code between lines 201-211 with:
```
$query = $this->db->query("SELECT column_name FROM information_schema.columns WHERE table_name='pastes' AND column_name='ip_address'");
if ($query->num_rows() == 0) {
    $fields = array(
        'ip_address' => array(
            'type' => 'VARCHAR',
            'constraint' => 45,
            'null' => true,
        ),
    );
    $this->dbforge->add_column('pastes', $fields);
}
```

Now, try to install again, and let me know if you get a different error, related to the `hits` column.

**Comment by TehPeGaSuS** [comment]
I got this with the code changes:
![Snip_Database_Error_2](https://github.com/user-attachments/assets/9b8e0442-e339-45fb-9a17-c2db50d122f3)

**Comment by MercanoGlobal** [comment]
Ok, then revert the previous suggested change to the original code:
```
        if (!$this->db->field_exists('ip_address', 'pastes')) {
            $this->load->dbforge();
            $fields = array(
                'ip_address' => array(
                    'type' => 'VARCHAR',
                    'constraint' => 45,
                    'null' => true,
                ),
            );
            $this->dbforge->add_column('pastes', $fields);
        }
```
And let's try something else.
Since this part of the code was not touched by our updates, I'm guessing this is a side effect caused by the new CodeIgniter framework, that has changed the Postgre Database Adapter.
- In `/system/database/drivers/postgre/postgre_driver.php` change the lines 423 and 438, to:
`WHERE LOWER("table_name") = '.$this->escape(strtolower($table));`

Please try to install again on a fresh database.

**Comment by TehPeGaSuS** [comment]
with the changes on `/system/database/drivers/postgre/postgre_driver.php` I'm getting the 1st error

**Comment by MercanoGlobal** [comment]
Weird... Without access and having never used Postgre, it's hard to debug this.
Did the previous Stikked work on Postgre?

**Comment by TehPeGaSuS** [comment]
Yes, it used to work with PostgreSQL.
I used it before I had to switch to PHP 8.x

**Comment by MercanoGlobal** [comment]
The only thing I can think of right now, is for you to remove the db prefix in the config `$config['db_prefix'] = '';` and try to install without it.
We will try to get our hands on a Postgre setup in the following days.

**Comment by TehPeGaSuS** [comment]
> The only thing I can think of right now, is for you to remove the db prefix in the config `$config['db_prefix'] = '';` and try to install without it. We will try to get our hands on a Postgre setup in the following days.

I'll try that and report back in a bit

**Comment by TehPeGaSuS** [comment]
I'll be damned...
Setting `$config['db_prefix']` to `''`, solved the issue with PostgreSQL.
A step close to fixing the issue :)

**Comment by MercanoGlobal** [comment]
Ok, let's do another blind test 😁 
In `/application/controllers/Main.php` replace lines `29-289` with the following code: https://pastebin.0bin.xyz/view/e6278c81
Then try to install on a clean PostgreSQL DB, with a `db_prefix` prefix set.

If it works, please try to do the same on SQLite and let me know if everything is ok.

PS: I need your help regarding this, since I don't have access to any Postgre/SQLite setups. Thanks!

**Comment by TehPeGaSuS** [comment]
I just tried the modifications and got the following errors, although I can see the paste field, navigate to recents, etc:
```
A PHP Error was encountered
Severity: Warning

Message: Undefined array key 1

Filename: controllers/Main.php

Line Number: 238

Backtrace:

File: /var/www/html/SNIP/htdocs/application/controllers/Main.php
Line: 238
Function: _error_handler

File: /var/www/html/SNIP/htdocs/index.php
Line: 315
Function: require_once
```
```

A PHP Error was encountered
Severity: Warning

Message: Attempt to read property "max_length" on null

Filename: controllers/Main.php

Line Number: 238

Backtrace:

File: /var/www/html/SNIP/htdocs/application/controllers/Main.php
Line: 238
Function: _error_handler

File: /var/www/html/SNIP/htdocs/index.php
Line: 315
Function: require_once
```

**Comment by MercanoGlobal** [comment]
Ok, now the same. In `/application/controllers/Main.php` replace those lines with the following code: https://pastebin.0bin.xyz/view/d9f70cd8
Then try a fresh install on a clean PostgreSQL DB, with a db_prefix prefix set.

**Comment by MercanoGlobal** [comment]
Ok, now the same. In `/application/controllers/Main.php` replace those lines with the following code: https://pastebin.0bin.xyz/view/8a43a13e
Then try a fresh install on a clean PostgreSQL DB, with a `db_prefix` set.

**Comment by TehPeGaSuS** [comment]
**Houston: We have liftoff!**

PostgreSQL and SQLite working without apparent issues!

Live on https://pastebin.0bin.xyz with the latest changes!

No Chrome DevTools errors, no server errors, no Apache errors!

**Comment by MercanoGlobal** [comment]
The release I create each time, is for the other (new) users that want to download the script. So that they get the latest and the best.
I should have marked the first release as Beta, considering the number of issues we fixed. But too late for that now.😃
