### ISSUE TITLE
snip.php.dist niot in lastest release

### ISSUE THREAD

**Issue by tcreek** [MercanoGlobal/SNIP#21]
The readme indicated to: 
`Copy application/config/snip.php.dist to application/config/snip.php`

However,

```
 ls htdocs/application/config/
ace_languages.php  codemirror_languages.php  database.php       geshi_languages.php  migration.php  routes.php   stikked.php.dist
auth_ldap.php      config.php                doctypes.php       hooks.php            mimes.php      smileys.php  user_agents.php
autoload.php       constants.php             foreign_chars.php  index.html           profiler.php   stikked.php
```

**Comment by MercanoGlobal** [comment]
Please download the latest SNIP release here: https://github.com/MercanoGlobal/SNIP/releases
And check again: https://github.com/MercanoGlobal/SNIP/tree/main/htdocs/application/config

Also, if you're trying to to upgrade from a previous release, note that the SNIP's config file has changed considerably from any previous ones. So you'll have to compare the settings you had in your previous config (stikked.php), with the new ones in **snip.php** and make the necessary adjustments.

**Comment by tcreek** [comment]
That is the version I downloaded.

You should stop being so dismissive 

I ended up using git clone instead of that "latest" release.
