### ISSUE TITLE
URLs for site returning 404

### ISSUE THREAD

**Issue by tcreek** [MercanoGlobal/SNIP#22]
I am using the default theme "bootstrap" already set in snip.php. I have tried the other themes, but getting the same result.

Following all URLs for the site are returning 404. 
Since it is currently set to 'bootstrap':

/trends which should be pointing to themes/bootstrap/views/trends.php

/lists which should be pointing to themes/bootstrap/views/list.php

/view which should be pointing to themes/bootstrap/views/view/view.php

I have looked in the access-log and error-log and I am not seeing anything.

**Comment by MercanoGlobal** [comment]
What you are experiencing is clearly a misconfiguration issue.
Please follow the config steps in **snip.php**, line-by-line & word-by-word.

Probably related to: **Base URL**

And here's an example of a SNIP setup running just fine: https://pastebin.0bin.xyz/

**Comment by tcreek** [comment]
I have gone over the snip.php several times. The base URL is set, and one of the first things done. I have tried it with a trailing / and without and the result is the same.

I see nothing else in that configuration file which could possibility affect sub directories.
