### ISSUE TITLE
URLs for site returning 404 - Reopen.

### ISSUE THREAD

**Issue by tcreek** [MercanoGlobal/SNIP#23]
Still same result

**Comment by MercanoGlobal** [comment]
It's hard to say what's causing this, without knowing what you're tying to do and what is your actual setup (related https://github.com/MercanoGlobal/SNIP/issues/22).
So please provide the following:
- Complete hosting details: Server type and version, PHP version, Database engine and version.
- Step-by-step description of what you are actually trying to do.
- Maybe the URL of your SNIP instance.

**Comment by tcreek** [comment]
Thanks for responding.

I started to post all the details of the setup including the virtual site set up here when I noticed an issue.

For Apache2, the SSL site configuration was missing the <directory> section. May be a good idea to mention in the docs that is needed also. 

Thanks again!
