### ISSUE TITLE
PHP Warning: Undefined array key 1

### ISSUE THREAD

**Issue by eekay35** [MercanoGlobal/SNIP#24]
Firstly, thank you for providing this updated Stikked code. Much appreciated!

I'm testing the latest release code (v1.0.0) on FreeBSD using PHP 8.2 and I'm receiving a warning upon viewing submitted paste:

```
PHP Warning: Undefined array key 1 on line 3523 in file application/libraries/geshi/geshi.php
```

I see mention that this code is PHP 8.3 compatible, so perhaps this works fine with 8.3 but not 8.2 (8.3 isn't the default in FBSD just yet so I haven't tested.)
I've added a "@" to variable which removed the warning but I'm unsure if this is the best solution:

```
--- htdocs/application/libraries/geshi/geshi.php.orig   2024-10-02 04:10:06 UTC 
+++ htdocs/application/libraries/geshi/geshi.php
@@ -3520,7 +3520,7 @@ class GeSHi {
             foreach ($this->language_data['OBJECT_SPLITTERS'] as $key => $splitter) {
                 if (false !== strpos($stuff_to_parse, $splitter)) {
                     if (!$this->use_classes) {
-                        $attributes = ' style="' . $this->language_data['STYLES']['METHODS'][$key] . '"';
+                        @$attributes = ' style="' . $this->language_data['STYLES']['METHODS'][$key] . '"';
                     } else {
                         $attributes = ' class="me' . $key . '"';
                     }
```

**Comment by MercanoGlobal** [comment]
Please provide a way to reproduce this, as we're not seeing such error on PHP 8.2.
What did you change in the config, and what type of paste did you create?

**Comment by eekay35** [comment]
Hi, MercanoGlobal. It looks like this might be related specifically to pastes for GO code. I didn't change anything in the config, but I did remove the "@" on line 3523 to test again. I tried multiple other languages and they seem to work fine. But, when I test with the GO language, I get the same error. I left the paste up and I'll leave the "@" out so you can see it if you'd like:

https://paste.purplehat.org/view/b41b73a2

**Comment by eekay35** [comment]
Updated and tested. Thank you! Will push the FreeBSD port now. Again, I appreciate your work!
