### ISSUE TITLE
[PostgreSQL] `ShortURL` shows "false" as value instead being hidden

### ISSUE THREAD

**Issue by TehPeGaSuS** [MercanoGlobal/SNIP#7]
While using PostgreSQL as database, and having `$config['disable_shorturl'] = true;`, `ShortURL` shows a value of false instead being hidden.

Same `snip.conf` as the one provided on #6

**Comment by MercanoGlobal** [comment]
In `/themes/stikkedizr/views/view/view.php` replace line 35 with: `<?php if(!empty($snipurl) && $snipurl !== false) { ?>` and let me know if it fixes the issue.

**Comment by TehPeGaSuS** [comment]
I get:
```
An uncaught Exception was encountered
Type: ParseError

Message: Unclosed '{' on line 35

Filename: /var/www/html/SNIP/htdocs/themes/stikkedizr/views/view/view.php

Line Number: 177

Backtrace:

File: /var/www/html/SNIP/htdocs/application/core/MY_Loader.php
Line: 33
Function: _ci_load

File: /var/www/html/SNIP/htdocs/application/controllers/Main.php
Line: 627
Function: view

File: /var/www/html/SNIP/htdocs/index.php
Line: 315
Function: require_once
```

**Comment by TehPeGaSuS** [comment]
Sorry, it has me who pasted it wrong. it doesn't seem to solve the issue though

**Comment by MercanoGlobal** [comment]
Ok, then please try this: `<?php if (!empty($snipurl) && $snipurl !== '0' && $snipurl !== false) { ?>`

**Comment by TehPeGaSuS** [comment]
What seems to work is `<?php if(!$this->config->item('disable_shorturl')) { ?>`.

**Comment by MercanoGlobal** [comment]
Yes, this works but partially.
If the ShortURL is enabled, but no short URL is available for the paste, it will return `0`, or in your case `false`. 
We need to make sure that the short URL section doesn't get displayed under any circumstance, if there's no short URL available for the paste.

Can you please try `<?php if (!$this->config->item('disable_shorturl') && !empty($snipurl)) { ?>`  ?

**Comment by TehPeGaSuS** [comment]
That has no effect, but `<?php if (!$this->config->item('disable_shorturl') && empty($snipurl)) { ?>` works. is this wrong too?

_NOTE: I'm no coder, just throwing ideas_

**Comment by MercanoGlobal** [comment]
Just as I figured.
The `&&` between the two conditions makes sure that the entire `if` statement is valid, if both conditions at the same time are valid.
In the PostgreSQL case, the `!empty($snipurl)`, in translation `not empty paste shortURL`, doesn't work...
I need to think about this more.

**Comment by TehPeGaSuS** [comment]
I tried both with `$config['disable_shorturl'] = true;` and `$config['disable_shorturl'] = false;` and the `ShortURL` isn't shown, though.

**Comment by MercanoGlobal** [comment]
Please try either this: `<?php if ($snipurl && $snipurl !== '0' && $snipurl !== false && $snipurl !== null) { ?>`
Or if that doesn't work, this: `<?php if (strlen((string)$snipurl) > 0 && $snipurl !== '0') { ?>`

**Comment by TehPeGaSuS** [comment]
That didn't work, either.

This one is being a bit more difficult.

**Comment by MercanoGlobal** [comment]
Yes, this is because of the way the original 'smart' Stikked developers, thought to store `NULL` values as `0` in the database, which breaks compatibility with PostgreSQL. `0` in Postgre is something, not nothing...

**Comment by TehPeGaSuS** [comment]
This seems to work (thanks, ChatGPT):
```
<?php if (!$this->config->item('disable_shorturl') && !empty($snipurl) && $snipurl !== 'false' && $snipurl !== '0') { ?>
```

**Comment by MercanoGlobal** [comment]
One of the hardest and stupidest things I had to debug, blindly... 😫 
@TehPeGaSuS Please test on the latest release, and let me know if there are any issues.

Time to get some rest.

**Comment by TehPeGaSuS** [comment]
So far all seems to work okay
